---
# Create Ansible Control Node VM for Semaphore
# This playbook creates a VM in Proxmox to host Semaphore

- name: Create Ansible Control Node VM in Proxmox
  hosts: localhost
  gather_facts: false
  
  vars:
    # VM Configuration
    vm_id: 200
    vm_name: ansible-control
    vm_node: Workstation-AMD  # Your Proxmox node name
    vm_cpus: 2
    vm_memory: 4096  # 4GB RAM
    vm_disk_size: 20  # 20GB disk
    
    # Network (adjust as needed)
    vm_ip: 192.168.1.100
    vm_gateway: 192.168.1.1
    vm_netmask: 24
    
  tasks:
    - name: Create VM for Semaphore
      debug:
        msg: |
          Creating VM with following specs:
          - ID: {{ vm_id }}
          - Name: {{ vm_name }}
          - Node: {{ vm_node }}
          - CPUs: {{ vm_cpus }}
          - Memory: {{ vm_memory }}MB
          - Disk: {{ vm_disk_size }}GB
          - IP: {{ vm_ip }}
          
    # Note: This would use the Proxmox MCP tools in practice
    # For now, we'll create a manual instruction set
    
    - name: VM Creation Instructions
      debug:
        msg: |
          ==========================================
          MANUAL VM CREATION REQUIRED
          ==========================================
          
          Please create a VM with these specifications:
          
          1. VM ID: {{ vm_id }}
          2. VM Name: {{ vm_name }}
          3. Node: {{ vm_node }}
          4. CPUs: {{ vm_cpus }}
          5. Memory: {{ vm_memory }}MB
          6. Disk: {{ vm_disk_size }}GB
          7. OS: Ubuntu 22.04 LTS
          
          Network Configuration:
          - IP: {{ vm_ip }}
          - Gateway: {{ vm_gateway }}
          - Netmask: /{{ vm_netmask }}
          
          After VM creation:
          1. Install Ubuntu 22.04 LTS
          2. Create user 'ubuntu' with sudo privileges
          3. Install openssh-server
          4. Copy your SSH public key to ~/.ssh/authorized_keys
          5. Update inventory file with correct IP address
          
          Then run: ./scripts/semaphore_bootstrap.sh
          ==========================================
