---
# Proxmox-based infrastructure inventory
all:
  children:
    proxmox_cluster:
      hosts:
        workstation-amd:
          ansible_host: 172.23.5.15
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    
    control_nodes:
      hosts:
        ansible-control:
          ansible_host: "172.23.5.22"  # ansible-control VM in VLAN 5
          ansible_user: ubuntuadmin
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_become: true
          
          # Semaphore configuration
          semaphore_hostname: semaphore.local
          semaphore_admin_user: admin
          semaphore_admin_email: admin@example.com
          semaphore_admin_password: "{{ vault_semaphore_admin_password | default('ChangeMePlease123!') }}"
          
          # Database configuration
          postgres_db: semaphore
          postgres_user: semaphore
          postgres_password: "{{ vault_postgres_password | default('ChangeMePlease456!') }}"
          
          # Version configuration
          semaphore_version: latest
          postgres_version: 16

  vars:
    # Global variables
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'